# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Tue Oct  9 17:34:06 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(683, 372)
        Dialog.setMinimumSize(QtCore.QSize(683, 372))
        Dialog.setMaximumSize(QtCore.QSize(683, 372))
        self.verticalLayout_7 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_j3 = QtGui.QLabel(Dialog)
        self.label_j3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j3.setObjectName(_fromUtf8("label_j3"))
        self.verticalLayout_4.addWidget(self.label_j3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pushButton_j3min = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j3min.sizePolicy().hasHeightForWidth())
        self.pushButton_j3min.setSizePolicy(sizePolicy)
        self.pushButton_j3min.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j3min.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j3min.setObjectName(_fromUtf8("pushButton_j3min"))
        self.horizontalLayout_8.addWidget(self.pushButton_j3min)
        self.pushButton_j3plus = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j3plus.sizePolicy().hasHeightForWidth())
        self.pushButton_j3plus.setSizePolicy(sizePolicy)
        self.pushButton_j3plus.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j3plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j3plus.setObjectName(_fromUtf8("pushButton_j3plus"))
        self.horizontalLayout_8.addWidget(self.pushButton_j3plus)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.slider_j3 = QtGui.QSlider(Dialog)
        self.slider_j3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_j3.sizePolicy().hasHeightForWidth())
        self.slider_j3.setSizePolicy(sizePolicy)
        self.slider_j3.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_j3.setMaximum(100)
        self.slider_j3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j3.setObjectName(_fromUtf8("slider_j3"))
        self.verticalLayout_4.addWidget(self.slider_j3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_j4 = QtGui.QLabel(Dialog)
        self.label_j4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j4.setObjectName(_fromUtf8("label_j4"))
        self.verticalLayout_5.addWidget(self.label_j4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.pushButton_j4min = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j4min.sizePolicy().hasHeightForWidth())
        self.pushButton_j4min.setSizePolicy(sizePolicy)
        self.pushButton_j4min.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_j4min.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j4min.setObjectName(_fromUtf8("pushButton_j4min"))
        self.horizontalLayout_7.addWidget(self.pushButton_j4min)
        self.pushButton_j4plus = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j4plus.sizePolicy().hasHeightForWidth())
        self.pushButton_j4plus.setSizePolicy(sizePolicy)
        self.pushButton_j4plus.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j4plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j4plus.setObjectName(_fromUtf8("pushButton_j4plus"))
        self.horizontalLayout_7.addWidget(self.pushButton_j4plus)
        spacerItem5 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.slider_j4 = QtGui.QSlider(Dialog)
        self.slider_j4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_j4.sizePolicy().hasHeightForWidth())
        self.slider_j4.setSizePolicy(sizePolicy)
        self.slider_j4.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_j4.setMaximum(100)
        self.slider_j4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j4.setObjectName(_fromUtf8("slider_j4"))
        self.verticalLayout_5.addWidget(self.slider_j4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem7 = QtGui.QSpacerItem(149, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_j2 = QtGui.QLabel(Dialog)
        self.label_j2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j2.setObjectName(_fromUtf8("label_j2"))
        self.verticalLayout_2.addWidget(self.label_j2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_j2min = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j2min.sizePolicy().hasHeightForWidth())
        self.pushButton_j2min.setSizePolicy(sizePolicy)
        self.pushButton_j2min.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j2min.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j2min.setObjectName(_fromUtf8("pushButton_j2min"))
        self.horizontalLayout_6.addWidget(self.pushButton_j2min)
        self.pushButton_j2plus = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j2plus.sizePolicy().hasHeightForWidth())
        self.pushButton_j2plus.setSizePolicy(sizePolicy)
        self.pushButton_j2plus.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j2plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j2plus.setObjectName(_fromUtf8("pushButton_j2plus"))
        self.horizontalLayout_6.addWidget(self.pushButton_j2plus)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.slider_j2 = QtGui.QSlider(Dialog)
        self.slider_j2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_j2.sizePolicy().hasHeightForWidth())
        self.slider_j2.setSizePolicy(sizePolicy)
        self.slider_j2.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_j2.setMaximum(100)
        self.slider_j2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j2.setObjectName(_fromUtf8("slider_j2"))
        self.verticalLayout_2.addWidget(self.slider_j2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem10)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_j1 = QtGui.QLabel(Dialog)
        self.label_j1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_j1.setObjectName(_fromUtf8("label_j1"))
        self.verticalLayout.addWidget(self.label_j1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.pushButton_j1min = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j1min.sizePolicy().hasHeightForWidth())
        self.pushButton_j1min.setSizePolicy(sizePolicy)
        self.pushButton_j1min.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j1min.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j1min.setObjectName(_fromUtf8("pushButton_j1min"))
        self.horizontalLayout_2.addWidget(self.pushButton_j1min)
        self.pushButton_j1plus = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_j1plus.sizePolicy().hasHeightForWidth())
        self.pushButton_j1plus.setSizePolicy(sizePolicy)
        self.pushButton_j1plus.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_j1plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_j1plus.setObjectName(_fromUtf8("pushButton_j1plus"))
        self.horizontalLayout_2.addWidget(self.pushButton_j1plus)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.slider_j1 = QtGui.QSlider(Dialog)
        self.slider_j1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_j1.sizePolicy().hasHeightForWidth())
        self.slider_j1.setSizePolicy(sizePolicy)
        self.slider_j1.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_j1.setMaximum(100)
        self.slider_j1.setSingleStep(2)
        self.slider_j1.setTracking(True)
        self.slider_j1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_j1.setInvertedAppearance(False)
        self.slider_j1.setInvertedControls(False)
        self.slider_j1.setTickPosition(QtGui.QSlider.NoTicks)
        self.slider_j1.setObjectName(_fromUtf8("slider_j1"))
        self.verticalLayout.addWidget(self.slider_j1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/all/schematic.svg")))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.pushButton_grab = QtGui.QPushButton(Dialog)
        self.pushButton_grab.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_grab.setObjectName(_fromUtf8("pushButton_grab"))
        self.verticalLayout_6.addWidget(self.pushButton_grab)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem14)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Smart Arm Controller Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j3.setText(QtGui.QApplication.translate("Dialog", "elbow_flex (Q/W)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j3min.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j3min.setShortcut(QtGui.QApplication.translate("Dialog", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j3plus.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j3plus.setShortcut(QtGui.QApplication.translate("Dialog", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j4.setText(QtGui.QApplication.translate("Dialog", "wrist_roll (1/2)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j4min.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j4min.setShortcut(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j4plus.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j4plus.setShortcut(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j2.setText(QtGui.QApplication.translate("Dialog", "shoulder_pitch (A/S)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j2min.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j2min.setShortcut(QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j2plus.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j2plus.setShortcut(QtGui.QApplication.translate("Dialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j1.setText(QtGui.QApplication.translate("Dialog", "shoulder_pan (Z/X)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j1min.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j1min.setShortcut(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j1plus.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_j1plus.setShortcut(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_grab.setText(QtGui.QApplication.translate("Dialog", "Grab (G)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_grab.setShortcut(QtGui.QApplication.translate("Dialog", "G", None, QtGui.QApplication.UnicodeUTF8))

import interface_rc
