(cl:defpackage motionControl-srv
  (:use )
  (:export
   "MOTIONCONTROL_MOVE"
   "<MOTIONCONTROL_MOVE-REQUEST>"
   "MOTIONCONTROL_MOVE-REQUEST"
   "<MOTIONCONTROL_MOVE-RESPONSE>"
   "MOTIONCONTROL_MOVE-RESPONSE"
   "MOTIONCONTROL_TIMEDMOVE"
   "<MOTIONCONTROL_TIMEDMOVE-REQUEST>"
   "MOTIONCONTROL_TIMEDMOVE-REQUEST"
   "<MOTIONCONTROL_TIMEDMOVE-RESPONSE>"
   "MOTIONCONTROL_TIMEDMOVE-RESPONSE"
  ))

