/* Auto-generated by genmsg_cpp for file /home/user/ros_workspace/Armed-turtlebot/mission_control/srv/generatePlan.srv */
#ifndef MISSION_CONTROL_SERVICE_GENERATEPLAN_H
#define MISSION_CONTROL_SERVICE_GENERATEPLAN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace mission_control
{
template <class ContainerAllocator>
struct generatePlanRequest_ {
  typedef generatePlanRequest_<ContainerAllocator> Type;

  generatePlanRequest_()
  {
  }

  generatePlanRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "mission_control/generatePlanRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::mission_control::generatePlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_control::generatePlanRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct generatePlanRequest
typedef  ::mission_control::generatePlanRequest_<std::allocator<void> > generatePlanRequest;

typedef boost::shared_ptr< ::mission_control::generatePlanRequest> generatePlanRequestPtr;
typedef boost::shared_ptr< ::mission_control::generatePlanRequest const> generatePlanRequestConstPtr;


template <class ContainerAllocator>
struct generatePlanResponse_ {
  typedef generatePlanResponse_<ContainerAllocator> Type;

  generatePlanResponse_()
  : status(0)
  {
  }

  generatePlanResponse_(const ContainerAllocator& _alloc)
  : status(0)
  {
  }

  typedef int8_t _status_type;
  int8_t status;


private:
  static const char* __s_getDataType_() { return "mission_control/generatePlanResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 status\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, status);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, status);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(status);
    return size;
  }

  typedef boost::shared_ptr< ::mission_control::generatePlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_control::generatePlanResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct generatePlanResponse
typedef  ::mission_control::generatePlanResponse_<std::allocator<void> > generatePlanResponse;

typedef boost::shared_ptr< ::mission_control::generatePlanResponse> generatePlanResponsePtr;
typedef boost::shared_ptr< ::mission_control::generatePlanResponse const> generatePlanResponseConstPtr;

struct generatePlan
{

typedef generatePlanRequest Request;
typedef generatePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct generatePlan
} // namespace mission_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mission_control::generatePlanRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mission_control::generatePlanRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mission_control::generatePlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::mission_control::generatePlanRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_control::generatePlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/generatePlanRequest";
  }

  static const char* value(const  ::mission_control::generatePlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mission_control::generatePlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::mission_control::generatePlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mission_control::generatePlanRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mission_control::generatePlanResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mission_control::generatePlanResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mission_control::generatePlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const  ::mission_control::generatePlanResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_control::generatePlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/generatePlanResponse";
  }

  static const char* value(const  ::mission_control::generatePlanResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mission_control::generatePlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 status\n\
\n\
\n\
";
  }

  static const char* value(const  ::mission_control::generatePlanResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mission_control::generatePlanResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mission_control::generatePlanRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct generatePlanRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mission_control::generatePlanResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct generatePlanResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<mission_control::generatePlan> {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::generatePlan&) { return value(); } 
};

template<>
struct DataType<mission_control::generatePlan> {
  static const char* value() 
  {
    return "mission_control/generatePlan";
  }

  static const char* value(const mission_control::generatePlan&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mission_control::generatePlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::generatePlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mission_control::generatePlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/generatePlan";
  }

  static const char* value(const mission_control::generatePlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mission_control::generatePlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::generatePlanResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mission_control::generatePlanResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/generatePlan";
  }

  static const char* value(const mission_control::generatePlanResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MISSION_CONTROL_SERVICE_GENERATEPLAN_H

