/* Auto-generated by genmsg_cpp for file /home/user/ros_workspace/Armed-turtlebot/mission_control/srv/motionControlStatusw.srv */
#ifndef MISSION_CONTROL_SERVICE_MOTIONCONTROLSTATUSW_H
#define MISSION_CONTROL_SERVICE_MOTIONCONTROLSTATUSW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace mission_control
{
template <class ContainerAllocator>
struct motionControlStatuswRequest_ {
  typedef motionControlStatuswRequest_<ContainerAllocator> Type;

  motionControlStatuswRequest_()
  {
  }

  motionControlStatuswRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "mission_control/motionControlStatuswRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_control::motionControlStatuswRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControlStatuswRequest
typedef  ::mission_control::motionControlStatuswRequest_<std::allocator<void> > motionControlStatuswRequest;

typedef boost::shared_ptr< ::mission_control::motionControlStatuswRequest> motionControlStatuswRequestPtr;
typedef boost::shared_ptr< ::mission_control::motionControlStatuswRequest const> motionControlStatuswRequestConstPtr;


template <class ContainerAllocator>
struct motionControlStatuswResponse_ {
  typedef motionControlStatuswResponse_<ContainerAllocator> Type;

  motionControlStatuswResponse_()
  : status(0)
  {
  }

  motionControlStatuswResponse_(const ContainerAllocator& _alloc)
  : status(0)
  {
  }

  typedef int8_t _status_type;
  int8_t status;


private:
  static const char* __s_getDataType_() { return "mission_control/motionControlStatuswResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "581cc55c12abfc219e446416014f6d0e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int8 status\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, status);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, status);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(status);
    return size;
  }

  typedef boost::shared_ptr< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_control::motionControlStatuswResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControlStatuswResponse
typedef  ::mission_control::motionControlStatuswResponse_<std::allocator<void> > motionControlStatuswResponse;

typedef boost::shared_ptr< ::mission_control::motionControlStatuswResponse> motionControlStatuswResponsePtr;
typedef boost::shared_ptr< ::mission_control::motionControlStatuswResponse const> motionControlStatuswResponseConstPtr;

struct motionControlStatusw
{

typedef motionControlStatuswRequest Request;
typedef motionControlStatuswResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct motionControlStatusw
} // namespace mission_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mission_control::motionControlStatuswRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::mission_control::motionControlStatuswRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/motionControlStatuswRequest";
  }

  static const char* value(const  ::mission_control::motionControlStatuswRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::mission_control::motionControlStatuswRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mission_control::motionControlStatuswResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const  ::mission_control::motionControlStatuswResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/motionControlStatuswResponse";
  }

  static const char* value(const  ::mission_control::motionControlStatuswResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 status\n\
\n\
\n\
";
  }

  static const char* value(const  ::mission_control::motionControlStatuswResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mission_control::motionControlStatuswRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControlStatuswRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mission_control::motionControlStatuswResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControlStatuswResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<mission_control::motionControlStatusw> {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::motionControlStatusw&) { return value(); } 
};

template<>
struct DataType<mission_control::motionControlStatusw> {
  static const char* value() 
  {
    return "mission_control/motionControlStatusw";
  }

  static const char* value(const mission_control::motionControlStatusw&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mission_control::motionControlStatuswRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::motionControlStatuswRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mission_control::motionControlStatuswRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/motionControlStatusw";
  }

  static const char* value(const mission_control::motionControlStatuswRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mission_control::motionControlStatuswResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const mission_control::motionControlStatuswResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mission_control::motionControlStatuswResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mission_control/motionControlStatusw";
  }

  static const char* value(const mission_control::motionControlStatuswResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MISSION_CONTROL_SERVICE_MOTIONCONTROLSTATUSW_H

