/* Auto-generated by genmsg_cpp for file /home/user/workspaces/ros/Armed-turtlebot/motionControl/srv/motionControl_forward.srv */
#ifndef MOTIONCONTROL_SERVICE_MOTIONCONTROL_FORWARD_H
#define MOTIONCONTROL_SERVICE_MOTIONCONTROL_FORWARD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace motionControl
{
template <class ContainerAllocator>
struct motionControl_forwardRequest_ {
  typedef motionControl_forwardRequest_<ContainerAllocator> Type;

  motionControl_forwardRequest_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  motionControl_forwardRequest_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef double _linear_type;
  double linear;

  typedef double _angular_type;
  double angular;


  typedef boost::shared_ptr< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motionControl::motionControl_forwardRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControl_forwardRequest
typedef  ::motionControl::motionControl_forwardRequest_<std::allocator<void> > motionControl_forwardRequest;

typedef boost::shared_ptr< ::motionControl::motionControl_forwardRequest> motionControl_forwardRequestPtr;
typedef boost::shared_ptr< ::motionControl::motionControl_forwardRequest const> motionControl_forwardRequestConstPtr;


template <class ContainerAllocator>
struct motionControl_forwardResponse_ {
  typedef motionControl_forwardResponse_<ContainerAllocator> Type;

  motionControl_forwardResponse_()
  {
  }

  motionControl_forwardResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motionControl::motionControl_forwardResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControl_forwardResponse
typedef  ::motionControl::motionControl_forwardResponse_<std::allocator<void> > motionControl_forwardResponse;

typedef boost::shared_ptr< ::motionControl::motionControl_forwardResponse> motionControl_forwardResponsePtr;
typedef boost::shared_ptr< ::motionControl::motionControl_forwardResponse const> motionControl_forwardResponseConstPtr;

struct motionControl_forward
{

typedef motionControl_forwardRequest Request;
typedef motionControl_forwardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct motionControl_forward
} // namespace motionControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_forwardRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const  ::motionControl::motionControl_forwardRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x144a16e4d6b53a0dULL;
  static const uint64_t static_value2 = 0xbadc2e617460a173ULL;
};

template<class ContainerAllocator>
struct DataType< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_forwardRequest";
  }

  static const char* value(const  ::motionControl::motionControl_forwardRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 linear\n\
float64 angular\n\
\n\
";
  }

  static const char* value(const  ::motionControl::motionControl_forwardRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_forwardResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::motionControl::motionControl_forwardResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_forwardResponse";
  }

  static const char* value(const  ::motionControl::motionControl_forwardResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::motionControl::motionControl_forwardResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::motionControl::motionControl_forwardRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControl_forwardRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::motionControl::motionControl_forwardResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControl_forwardResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<motionControl::motionControl_forward> {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_forward&) { return value(); } 
};

template<>
struct DataType<motionControl::motionControl_forward> {
  static const char* value() 
  {
    return "motionControl/motionControl_forward";
  }

  static const char* value(const motionControl::motionControl_forward&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<motionControl::motionControl_forwardRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_forwardRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<motionControl::motionControl_forwardRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_forward";
  }

  static const char* value(const motionControl::motionControl_forwardRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<motionControl::motionControl_forwardResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_forwardResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<motionControl::motionControl_forwardResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_forward";
  }

  static const char* value(const motionControl::motionControl_forwardResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MOTIONCONTROL_SERVICE_MOTIONCONTROL_FORWARD_H

