/* Auto-generated by genmsg_cpp for file /home/user/workspaces/ros/Armed-turtlebot/motionControl/srv/motionControl_right.srv */
#ifndef MOTIONCONTROL_SERVICE_MOTIONCONTROL_RIGHT_H
#define MOTIONCONTROL_SERVICE_MOTIONCONTROL_RIGHT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace motionControl
{
template <class ContainerAllocator>
struct motionControl_rightRequest_ {
  typedef motionControl_rightRequest_<ContainerAllocator> Type;

  motionControl_rightRequest_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  motionControl_rightRequest_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef double _linear_type;
  double linear;

  typedef double _angular_type;
  double angular;


  typedef boost::shared_ptr< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motionControl::motionControl_rightRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControl_rightRequest
typedef  ::motionControl::motionControl_rightRequest_<std::allocator<void> > motionControl_rightRequest;

typedef boost::shared_ptr< ::motionControl::motionControl_rightRequest> motionControl_rightRequestPtr;
typedef boost::shared_ptr< ::motionControl::motionControl_rightRequest const> motionControl_rightRequestConstPtr;


template <class ContainerAllocator>
struct motionControl_rightResponse_ {
  typedef motionControl_rightResponse_<ContainerAllocator> Type;

  motionControl_rightResponse_()
  {
  }

  motionControl_rightResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motionControl::motionControl_rightResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct motionControl_rightResponse
typedef  ::motionControl::motionControl_rightResponse_<std::allocator<void> > motionControl_rightResponse;

typedef boost::shared_ptr< ::motionControl::motionControl_rightResponse> motionControl_rightResponsePtr;
typedef boost::shared_ptr< ::motionControl::motionControl_rightResponse const> motionControl_rightResponseConstPtr;

struct motionControl_right
{

typedef motionControl_rightRequest Request;
typedef motionControl_rightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct motionControl_right
} // namespace motionControl

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_rightRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const  ::motionControl::motionControl_rightRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x144a16e4d6b53a0dULL;
  static const uint64_t static_value2 = 0xbadc2e617460a173ULL;
};

template<class ContainerAllocator>
struct DataType< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_rightRequest";
  }

  static const char* value(const  ::motionControl::motionControl_rightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 linear\n\
float64 angular\n\
\n\
";
  }

  static const char* value(const  ::motionControl::motionControl_rightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::motionControl::motionControl_rightRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::motionControl::motionControl_rightResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::motionControl::motionControl_rightResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_rightResponse";
  }

  static const char* value(const  ::motionControl::motionControl_rightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::motionControl::motionControl_rightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::motionControl::motionControl_rightResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::motionControl::motionControl_rightRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControl_rightRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::motionControl::motionControl_rightResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct motionControl_rightResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<motionControl::motionControl_right> {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_right&) { return value(); } 
};

template<>
struct DataType<motionControl::motionControl_right> {
  static const char* value() 
  {
    return "motionControl/motionControl_right";
  }

  static const char* value(const motionControl::motionControl_right&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<motionControl::motionControl_rightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_rightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<motionControl::motionControl_rightRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_right";
  }

  static const char* value(const motionControl::motionControl_rightRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<motionControl::motionControl_rightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "144a16e4d6b53a0dbadc2e617460a173";
  }

  static const char* value(const motionControl::motionControl_rightResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<motionControl::motionControl_rightResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "motionControl/motionControl_right";
  }

  static const char* value(const motionControl::motionControl_rightResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MOTIONCONTROL_SERVICE_MOTIONCONTROL_RIGHT_H

